spring:
  application:
    name: spring-rdf4j-example

rdf4j:
  spring:
    repository:
      remote:
        manager-url: http://localhost:3030/ds/update
    tx:
      enabled: false
    pool:
      enabled: false # Enabling the pool will cause the test to timeout
